export const AUDIT_POST_CREATED = "AUDIT_POST_CREATED";
export const ACCEPT_BID_FOR_POST = "BID_FOR_POST_ACCEPTED";
export const EXTENDED_TIMELINE_BY_AUDITOR = "REQUEST_FOR_EXTENDED_TIMELINE";
export const EXTENDED_POST_BY_PATRON = "EXTENDED_TIMELINE_REQUEST_APPROVED";
export const SUBMIT_AUDIT_REPORT_BY_AUDITOR = "AUDIT_REPORT_SUBMITTED";
export const ACCEPT_AUDIT_REPORT_BY_PATRON = "AUDIT_REPORT_ACCEPTED";
export const AUDIT_REPORT_DECLINE_BY_PATRON = "AUDIT_REPORT_DECLINED";
export const CLAIM_AMOUNT_BY_PATRON = "AMOUNT_CLAIMED";
export const ARBITOR_VOTE = "ARBITOR_VOTE";










